### ISSUE TITLE
[bug] zoom to selection and deselect item fails

### ISSUE THREAD

**Issue by rusak47** [lkosson/gced#2]
Hello! 
I've noticed a few more problems:

- The graphical editor doesn't center on the G-code picture after the initial opening of a G-code file.
- "Zoom to selection" doesn't zoom to the selection, and there is no separate zoom in/out button or shortcut.
- It's impossible to deselect some elements from multiple selection.

[screen-recorder-sun-sep-17-2023-22-49-22.webm](https://github.com/lkosson/gced/assets/8426197/446b2c3d-03f1-497f-8eb0-a32cd95a1069)

**Comment by lkosson** [comment]
I have published a 1.2.1 release which fixes deselecting lines by CTRL-clicking them and adds zoom in/out menu items and keyboard shortcuts.

`Pan to selection` (`SHIFT-H`) should work properly. It deliberately keeps zoom level constant.

When opening a new file, there was a some nasty edge case preventing automated pan/zoom to show whole project. Sadly, I can't remember now what it was and why I had to disable it. As for now, please use `Pan/zoom to fit all` (`H`) manually after opening a new file.
