### ISSUE TITLE
[enhancement] allow to move view and selection mode configuration

### ISSUE THREAD

**Issue by rusak47** [lkosson/gced#3]
- There is no "move view" action, which would be useful for zooming (#1). Perhaps consider adding a choice between "select" and "move" modes or attaching it to the left mouse button, which is currently unused.

- Another cool feature could be configuring G-codes for selection (multiple selection). When doing multiple selections, most of the time, I need to select only cutting moves (G1-3), but, of course, there should be a way to maintain the current behavior, too.

(see https://github.com/lkosson/gced/issues/1#issuecomment-1722899482)

**Comment by lkosson** [comment]
* You can move view using middle mouse button.
 * When you drag-select with left mouse button while holding left-Alt, you'll select only G1, G2 and G3 operations.

Left-Alt key modifier also works in other modes, e.g. when creating an arc using `2` or `3` or editing it using `Shift-E`, holding Alt switches from defining arc by three points to defining arc by beginning, end and center. When editing arc endpoint using just `E`, holding Alt switches from moving the endpoint to modifying the sweep angle.

I with there were some tooltips or context hints about those functions, but as of now, there aren't.

**Comment by rusak47** [comment]
> * When you drag-select with left mouse button while holding left-Alt, you'll select only G1, G2 and G3 operations.

Thanks, that works. Although there are no tooltips, you can add them to the readme. I believe it's better than nothing.
